[target.x86_64-unknown-linux-musl]
image = "ghcr.io/penumbra-x/rust-musl-cross:x86_64-unknown-linux-musl"

[target.aarch64-unknown-linux-musl]
image = "ghcr.io/penumbra-x/rust-musl-cross:aarch64-unknown-linux-musl"